okta/okta-auth-js

lib/index.js
test/xhr/mfa-challenge-sms.js

bacon: test
resolves: OKTA-89062
@rchild-okta @Ujjwalreddy-okta 
This handles parsing potential `null`s in our Auth API responses. A stack overflow occurs without this fix.

Fixed null parsing

---

lib/token.js
test/spec/oauth.js

bacon:test
Resolves: OKTA-91565
@rchild-okta 
The nonce is sent in the jwt, not the postMessage response or url hash.

Check for nonce in jwt, not postMessage response

---

.eslintignore
.gitignore
lib/http.js
lib/token.js
lib/tx.js
package.json
test/spec/general.js
webpack.AMDJqueryQ.config.js
webpack.common.config.js
webpack.config.js
webpack.test.config.js
writeConfig.js

Resolves: OKTA-94206
This fixes an issue where simply calling 'require' on the npm version of the sdk causes SDK_VERSION and other globals variables to be undefined. Webpack usually defines these variables using the DefinePlugin; now we build a config that can be 'require'd without webpack.
@rchild-okta 
@alexeystadnikov-okta

Remove DefinePlugin to fix undefined SDK_VERSION

---

lib/clientBuilder.js
lib/token.js
test/spec/oauth.js
test/spec/token.js
test/util/oauthUtil.js
test/util/tokens.js
webpack.test.config.js

Resolves: OKTA-94707
Most of this change is in our tests. I moved the oauth setup functions to a common module (oauthUtils.js) and the standard tokens to the tokens.js file.
@rchild-okta 
@stsai-okta

Added token.getWithoutPrompt

---

lib/token.js
test/spec/oauth.js
test/spec/token.js
test/util/oauthUtil.js
test/util/tokens.js

Resolves: OKTA-95512
The point is to add access_token support to the sdk, so let's do that!
@rchild-okta 
@stsai-okta

Add access_token support to getWithoutPrompt

---

lib/clientBuilder.js
lib/cookies.js
lib/token.js
package.json
test/spec/general.js
test/spec/oauth.js
test/spec/token.js
test/util/oauthUtil.js
test/util/tokens.js
test/util/util.js
webpack.config.js

Resolves: OKTA-94708
@rchild-okta 
@alexma-okta

Added token.getWithPopup, token.getWithRedirect, and token.parseFromUrl

---

.eslintignore
.gitignore
lib/http.js
lib/token.js
lib/tx.js
writeConfig.js

Resolves: OKTA-96664
This allows importing via webpack without using the json-loader
@rchild-okta 
@manueltanzi-okta

Generate config.js instead of config.json

---

.eslintrc.json
lib/TokenManager.js
lib/clientBuilder.js
lib/tokenStorageBuilder.js
package.json
test/spec/tokenManager.js
test/util/oauthUtil.js
test/util/tokens.js
test/util/util.js

Resolves: OKTA-94714
@rchild-okta 
@royalchan-okta 
@alexma-okta

Added tokenManager.add/get/remove

---

lib/token.js
test/spec/token.js
test/util/tokens.js

Resolves: OKTA-100899
Uses query as default responseMode if only an authorization code is requested, otherwise defaults to fragment. Also adds the ability to parse an authorization code from a url fragment.
@rchild-okta 
@haishengwu-okta

Added auth code support

---

.eslintrc.json
lib/clientBuilder.js
lib/http.js
lib/session.js
lib/token.js
test/spec/token.js
test/util/util.js
test/xhr/error-userinfo-insufficient-scope.js
test/xhr/error-userinfo-invalid-token.js
test/xhr/userinfo.js

Resolves: OKTA-100558
@rchild-okta 
@haishengwu-okta 
http://developer.okta.com/docs/api/resources/oidc.html#get-user-information

Added token.getUserInfo

---

lib/cookies.js
lib/token.js
package.json
test/spec/token.js
test/spec/tokenManager.js
test/util/oauthUtil.js

Resolves: OKTA-104490
In order to validate id_tokens sent to the server via query responses, we need to pass cookies with the state and nonce. We store stringified JSON in `okta-oauth-redirect-params`, but this is non-trivial to parse on the server, so I've added `okta-oauth-state` and `okta-oauth-nonce` to make this easier.
I also changed the path of the cookies to match root. Without the root path, the cookies aren't parseable from different url paths.
@rchild-okta @magizh-okta

Added state and nonce cookies for token validation

---

webpack.config.js

Resolves: OKTA-104120
@rchild-okta @magizh-okta 
This changes future distributed assets from:
> https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/x.x.x/OktaAuth.min.js
to:
> https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/x.x.x/okta-auth-js.min.js
in order to match okta-signin-widget:
> https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/x.x.x/js/okta-sign-in.min.js
edit: just noticed our okta-signin-widget name is pretty strange itself. Should we change "okta-sign-in.min.js" to "okta-signin-widget.min.js"?

Change distributed filename to okta-auth-js

---

lib/TokenManager.js
lib/http.js
lib/oauthUtil.js
lib/storageUtil.js
lib/util.js
test/spec/oauthUtil.js
test/spec/tokenManager.js
test/util/oauthUtil.js
test/util/util.js

localStorage and sessionStorage aren't available in some scenarios on IE11. This commit handles those scenarios by first attempting to fallback to sessionStorage, then cookies if sessionStorage doesn't exist.
Tested with widget in IE11 after [starting using these instructions](https://marckean.com/2010/12/17/run-internet-explorer-as-the-local-system-account/):
Resolves: OKTA-105205

:bug: Checks for IE11 localStorage

---

README.md

All of the changes in README.md are to allow it to be rendered on GitHub with GFM and also on developer.okta.com with Kramdown
Most changes are made to the spacing. GFM seems to be okay with the following:
```
- List Item
Text indented with FOUR spaces
```
While Kramdown seems to require that indented text to have the same spacing as the item they are under, like this:
```
- List item
Text indented with TWO spaces
```
Also added were special HTML comments`` and `` which are used to mark text which will _not_ be transcluded into developer.okta.com
Since developer.okta.com templates include the title of the page, I removed the name of the project from the first `<h1>` tag (`#`) and renamed it "Introduction". 
Lastly, GFM seems to be okay with list items that use close parens (i.e.: `1)`, …

Fixes to allow README.md to be transcluded into developer.okta.com

---

README.md
lib/clientBuilder.js
lib/http.js
lib/util.js
test/spec/util.js
test/spec/webfinger.js
test/xhr/webfinger.js

:seedling: Adds support for Webfinger API calls

---

README.md
lib/clientBuilder.js
lib/tx.js
test/spec/fingerprint.js

Add `sendFingerprint` option to attach a fingerprint to the `signIn` call

:seedling: Add sendFingerprint option to signIn

---

lib/clientBuilder.js
test/spec/errors.js

- Checks for `*-admin.*` when attempting to init the `OktaAuth` object.

:white_check_mark: Check for -admin in URL during init

---

README.md
lib/tx.js
test/spec/mfa-challenge.js
test/spec/mfa-required.js

:seedling: Adds support for autoPush url param in poll and verify functions

---

.eslintrc.json
lib/clientBuilder.js
lib/http.js
test/spec/general.js

This allows other libraries to prefix the user agent, rather than overwriting it entirely with passed options

feat: Allow user agent to be modified

---

lib/clientBuilder.js
test/spec/fingerprint.js

Fixes an issue where the `iframe` triggering the fingerprint request was receiving an invalid origin. This was caused by attempting to `postMessage` to an incorrect origin.
[OKTA-163625](https://oktainc.atlassian.net/browse/OKTA-163625)

:bug: Update postMessage to call correct origin

---

jquery/index.js
jquery/jqueryRequest.js
lib/TokenManager.js
lib/clientBuilder.js
lib/cookies.js
lib/crypto.js
lib/errors/AuthApiError.js
lib/errors/AuthPollStopError.js
lib/errors/AuthSdkError.js
lib/errors/OAuthError.js
lib/http.js
lib/index.js
lib/license-header.txt
lib/oauthUtil.js
lib/session.js
lib/storageBuilder.js
lib/storageUtil.js
lib/token.js
lib/tx.js
lib/util.js
none/index.js
reqwest/index.js
reqwest/reqwestRequest.js

- Updates date in source file headers to use `2015-present` or `2018-present`
- Modifies production build license header to use `2015-present` instead of `2015-2016`
Resolves: #97

:memo: Add/update license headers

---

README.md
lib/clientBuilder.js
test/spec/errors.js
test/spec/token.js
test/spec/tokenManager.js

Infer the required `url` parameter if `issuer` is given during client instantiation.
For OAuth flows, it is encouraged to request tokens from the `/token` endpoint via a custom authorization server, as opposed to Okta's authorization server for API AM use cases.
This change simplifies the setup for developers, and eliminates confusion on **which** URL goes where, as they only need to inject **one** URL.
```javascript
var config = {
url: 'https://{yourOktaDomain}',
clientId: 'your-client-id',
redirectUri: 'https://your.redirect.uri/redirect',
issuer: 'https://{yourOktaDomain}/oauth2/default'
};
var authClient = new OktaAuth(config);
```
```javascript
var config = {
issuer: 'https://{yourOktaDomain}/oauth2/default',
clientId: 'your-client-id',
redirectUri: …
```

:seedling: Infer url from issuer during creation

---

lib/cookies.js
lib/storageUtil.js
lib/token.js
package.json
test/spec/cookies.js
test/spec/oauthUtil.js
test/spec/token.js
test/spec/tokenManager.js
test/util/oauthUtil.js
test/util/util.js

Updates cookie storage to be compliant with [RFC 6265](https://tools.ietf.org/html/rfc6265#section-4.1.1).
We're now using a new dependency - [`js-cookie`](https://github.com/js-cookie/js-cookie) to handle storing/retrieving objects from `document.cookie`. This creates a slightly larger build:
| File                                       | Size             | New Size   |
|  :------------------------  | :----------: | :---------: |
| `okta-auth-js.min.js`         | **63KB**   |  **63KB**  |
| `okta-auth-js.min.js.map` | **465KB** | **470KB** |
- #112 
- #100

:seedling: Use cookie lib for RFC 6265 compliance

---

package.json

Rev up version of okta-auth-js to 1.18.0 to handle an implicit upgrade to @okta/ci-update-package that handles release NPM packages differently.
Resolves: OKTA-178456
Primary reviewers:
@rchild-okta 
@jmelberg-okta 
@okta/travisci

:arrow_up: Rev up version to handle @okta/ci-update-package upgrade

---

README.md
lib/TokenManager.js
test/spec/tokenManager.js
test/util/oauthUtil.js

Modifies token retrieval methods to account for asynchronous token refresh.
Previously, `setTimeout` was used to continuously **refresh** the tokens when they expired. In some cases, retrieving a token after token expiration created a refresh/return race condition.
Modifying the `tokenManager` to return a `Promise` with respect to refreshing the token as needed, reassures that tokens returned via `authClient.tokenManager.get('tokenName')` are valid.
Previously:
```javascript
const accessToken = authClient.tokenManager.get('accessToken');
```
Now:
```javascript
// ES2016+
const accessToken = await authClient.tokenManager.get('accessToken');
// Handle as a promise
authClient.tokenManager.get('accessToken')
.then(function(accessToken) {
console.log(accessToken);
});
```
- …

:bug: Make token retrieval async

---

README.md
lib/clientBuilder.js
lib/oauthUtil.js
lib/token.js
test/spec/oauthUtil.js
test/spec/token.js
test/util/oauthUtil.js

Grants developers the ability to _disable_ `idToken` signature validation for testing purposes and browser support.
> This feature will be undocumented, as it isn't compliant via [Implicit ID Token Validation](http://openid.net/specs/openid-connect-core-1_0.html#ImplicitIDTValidation)
The `ignoreSignature` param can be passed in during either **client configuration** or **token validation**.
```javascript
var authClient =  new OktaAuth({
url: 'https://{yourOktaDomain}',
ignoreSignature: true
});
// An idToken returned from Okta will not have the signature verified.
```
```javascript
var validationOptions = {
ignoreSignature: true
};
authClient.token.verify(idToken, validationOptions)
.then(function() {
console.log('Token is valid!');
})
.catch(function(err) {
console.error(err);
});
```
- …

Provide option to skip idToken signature validation

---

README.md
lib/TokenManager.js
lib/clientBuilder.js
lib/token.js
test/spec/token.js
test/spec/tokenManager.js
test/util/oauthUtil.js

To make it more clear to developers, token methods have been renamed as follows to help imply that tokens are being **renewed** using the Okta session, not a `refreshToken`
* `token.refresh` ➡️  `token.renew`
* `tokenManager.refresh` ➡️ `tokenManager.renew`
* The `refreshed` event is now `renewed`
* `autoRefresh` ➡️ `autoRenew`
This PR is broken into the following commits:
* [`5fb8d37`](https://github.com/okta/okta-auth-js/commit/5fb8d376edf604c2cc278e1bec8ed3a90463d097) - Renames `autoRefresh` to `autoRenew`
* [`0692261`](https://github.com/okta/okta-auth-js/commit/069226164ca8eef4ed3297c8bcfb3ee0dd307974) - Renames all tokenManager refresh methods to renew
* [`cec65a9`](https://github.com/okta/okta-auth-js/commit/cec65a9d65b90c65ba8e9ba75d96db32e363459a) - Rename `token.refresh` to …

Renames refresh to renew

---

README.md

Per conversations today:
- Update the two configuration examples to explain why you'd use `url` vs `issuer`
- Temporarily remove CDN instructions, because the CDN artifact will not immediately be available after NPM release.  We will add it back in when it's available.

2.0 Readme updates

---

lib/TokenManager.js
test/spec/tokenManager.js

1) Add an unexpired access token to the token manager.
2) Call `auth.getAccessToken()` before the access token expires.
- Token is retrieved from storage.
- No HTTP request is made to retrieve a new access token from the issuing server.
- Token is retrieved from storage.
- HTTP request is made.
The problem is in the `getAsync()` function in the `TokenManager`. Although it correctly retrieves the token from storage when the token has not expired, the execution of the function does not end when the promise is resolved. Consequently, the code to renew the token is executed and a new access token is retrieved from the issuer.
I think this new behavior is preferable, since it doesn't result in excessive requests to the auth server.
My tests don't exactly conform to the style established in the …

Prevent token renewal when token is not expired

---

.travis.yml
Gruntfile.js
lib/token.js
lib/util.js
package-lock.json
package.json

Updates and removes outdated `devDependencies`.
> TODO: We will need to update (or choose to move away from) `grunt-contrib-jasmine` to suppress all `npm audit` messages. This work will be picked up in a follow-up PR.

:arrow_up: Update dependencies

---

lib/token.js
test/spec/token.js

Resolves the issue described in #160

Ignore signature not set in get with redirect

---

package.json

- set coverage repo path
- enable silent for ci rather dev when detail information might be useful.

:bug: Fix the issue that cant generate coverage report

---

lib/token.js
test/spec/token.js

Scrub passed in `oauthOptions` through a utility method to remove `null` and `undefined` values.
This will resolve an issue where where the `null` type for `scopes` is treated as a `Array` object [here](https://github.com/okta/okta-auth-js/blob/master/lib/token.js#L258).
- This fix is needed for [#569](https://github.com/okta/okta-signin-widget/issues/569)

Scrub null/undefined values from authorize requests

---

README.md

Calls out when token validation is performed automatically in the following methods:
- `token.getWithRedirect`
- `token.getWithoutPrompt`
- `token.getWithPopup`
- `token.parseFromUrl`
- #151

chore: Callout token validation in README

---

lib/storageUtil.js
test/spec/tokenManager.js
test/util/oauthUtil.js

Fixes an issue where checking if `localStorage` and/or `sessionStorage` was returning `true`, even though it cannot be written to.
See: 
- https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API#Private_Browsing_Incognito_modes
Here is an example using iOS 10 Safari:
- [Video](http://g.recordit.co/yK7g1YWGDR.gif)

fix: Fixes an issue where default storage was read-only

---

lib/token.js
test/spec/token.js

Due to a bug in our implementation of #171 - silent token renewal or [`getWithoutPrompt`](https://github.com/okta/okta-auth-js/blob/master/lib/token.js#L457-L461) calls would throw errors.
Until there is a better story around ignoring/fixing `null` values, this change will be reverted.

Revert 171 jm scrub auth params

---

CHANGELOG.md

Updates changelog entries to reflect changes with `2.1.0` and `2.2.0`.

Updates changelog for @okta/okta-auth-js@2.2.0

---

lib/util.js

Hey,
as of the documentation I should be able to use okta-auth-js from nodejs (at least in part). In practice this leads to an exception very fast because 'window' is not defined in node.
Best
Christian

Removed dependency on global window object.

---

CHANGELOG.md
README.md
package.json

* When deprecated `ajaxRequest` was passed to config, the logger for the deprecate message was still using window.console. In this new version the logger is made isomorphic so that issue is fixed.
* Also updateds README to highlight deprecation of `ajaxRequest` parameter in favor of `httpRequestClient`.
@robertjd @brettritter-okta

release: Publish okta-auth-js v2.3.1

---

README.md

As discussed with @robertjd , we gonna remove it for now only from the README, and we are gonna remove it from the code when we will bump okta-auth-js to 3.x (https://oktainc.atlassian.net/browse/OKTA-219719), since that would be a breaking change.
Jira: https://oktainc.atlassian.net/browse/OKTA-219718
@haishengwu-okta @robertjd @royalchan-okta 
@antonshyltsev-okta

chore: Remove requestContext from README

---

.npmignore

Add `scripts` to the .npmignore list to prevent them to go in the npm artifact. Customers don't need our build scripts.
Jira: https://oktainc.atlassian.net/browse/OKTA-217531
@gowthamidommety-okta @robertjd

chore: Prevents scripts to go to the npm artifact

---

lib/TokenManager.js
lib/browser/browser.js
lib/clock.js
lib/oauthUtil.js
test/app/src/index.js
test/spec/clock.js
test/spec/features.js
test/spec/oauthUtil.js
test/spec/tokenManager.js
test/util/oauthUtil.js
test/util/util.js

- fixes logic involving 'maxClockSkew' to instead use a 'localClockOffset'. This value may be positive or negative and should be calculated (somehow)
- adds a new method `sdk.clock.now()` which will return the adjusted local time, *in seconds*. This value can be directly compared to `token.expiresAt`
- fixes many tests which were silently catching errors
- corrects regression involving custom key names on token manager
This PR does not contain any logic for calculating or setting the 'localClockOffset'. Until there is a method for this, the value will be 0 in production. This will still fix an  issue caused by misuse of 'maxClockSkew'

fix: Misuse of 'maxClockSkew'. Adds support for 'localClockOffset' option

---

README.md
lib/TokenManager.js
lib/browser/browser.js
lib/clock.js
lib/util.js
test/spec/clock.js
test/spec/tokenManager.js
test/spec/util.js
test/util/util.js

- Adds new TokenManager option 'expireEarly', with a default value of 30 (seconds)

Add 'expireEarly' option. Document 'maxClockSkew' option

---

.gitignore
README.md
lib/browser/browser.js
lib/pkce.js
lib/token.js
test/app/README.md
test/app/src/index.js
test/app/src/testApp.js
test/app/webpack.config.js
test/karma/spec/loginFlow.js
test/karma/spec/renewToken.js
test/spec/features.js
test/spec/pkce.js
test/spec/token.js

This fixes non-SPA apps which are using the auth-js library (including SIW). The responseMode was being incorrectly set to "fragment" in getWithRedirect()
- restores test for non PKCE "code" flow
- restores previous behavior, where responseMode is set to "query" if responseType is "code" (and not using PKCE)
- adds some tests for PKCE

Fix: getWithRedirect: set responseMode to "query" for non PKCE code flow

---

jest.server.js
lib/browser/browser.js
lib/token.js
test/spec/browser.js
test/spec/token.js

- grantType will be deprecated in v3.0 https://oktainc.atlassian.net/browse/OKTA-242989
- simplify getDefaultOauthParams()
- add additional testing around constructor / options

Add support for "grantType" as alias for PKCE

---

lib/browser/browser.js
lib/tx.js

- Update API url to `/idp/idx/introspect`
- This is the only place where the url is hardcoded to hit `/idx`
- Note: we also want to publish a version of auth-js with this change to consume in the widget for OIE, since currently we are using version of auth js in the widget that is based on a hash and is throwing errors on bacon during build. 
@haishengwu-okta @royalchan-okta @VadymYaremchuk-okta

Add introspect API

---

test/util/util.js

Exceptions with mock fetch were being swallowed. Return the promise instead of using `done()` callback

test fix: return exceptions in mock fetch

---

.vscode/launch.json
lib/TokenManager.js
lib/token.js
package.json
test/.eslintrc.json
test/spec/token.js
test/spec/tokenManager.js
test/util/oauthUtil.js
yarn.lock

- fixes condition where token request would fail, but not reject. This occurred when the authorizeUrl saved in the token does not match the configured issuer.
- fixes behavior in TokenManager: multiple calls to renew() while a request is in process should not produce extra requests, but each caller should receive the same promise.

fix: token renew promise sometimes does not resolve

---

README.md
lib/TokenManager.js
test/app/src/testApp.js
test/karma/spec/renewToken.js
test/spec/tokenManager.js

Add some tests and minor documentation additions around TokenManager "error" event. This event is emitted when `renew()` fails because session is expired or invalid.
Will also remove token and emit "error" event if, while renewing, an `AuthSdkError` is thrown.

Improve error handling, doc, add tests for TokenManager "error" event

---

lib/tx.js
test/spec/__snapshots__/mfa-challenge.js.snap
test/spec/mfa-challenge.js

* If a callback is passed to polling function during mfa challenge, the callback is invoked on
every successful poll with the transaction as argument.
* This is needed to know if the response info changed during poll.
eg) OV risk scoring number challenge flow.
https://okta.app.box.com/s/yhybly12s4jne89fsoc41rgkqxpmd2g8

Add support to pass callback to poll function

---

test/app/package.json
test/app/public/implicit/callback/index.html
test/app/public/index.html
test/app/src/testApp.js
test/app/src/tokens.js
test/e2e/.babelrc
test/e2e/package.json
test/e2e/pageobjects/OktaHome.js
test/e2e/pageobjects/OktaLogin.js
test/e2e/pageobjects/TestApp.js
test/e2e/specs/login.js
test/e2e/specs/tokens.js
test/e2e/util/appUtils.js
test/e2e/util/browserUtils.js
test/e2e/util/loginUtils.js
test/e2e/wdio.conf.js
yarn.lock

- Adds e2e tests for the scenario where a user has logged from the okta user home page. In this case, attempting to renew a token should give us an error, and we can recognize that the user is no longer authenticated
- Fix for some flakiness in e2e test harness app (apparently) caused by the use of `h1` and `h2` tags. This is probably related to margin-collapse. These tags have been removed.
- Converts e2e specs to `async/await` syntax. This makes more sense for debugging and removes some "magic". We also seem to get better error stacks.

Add tests for external logout

---

packages/okta-auth-js/lib/token.js
packages/okta-auth-js/test/spec/token.js
packages/okta-auth-js/test/spec/tokenManager.js

- behavior is seen on firefox, not chrome. Popup blocker leaves us with an "undefined" window object
- fix potential infinite loop with closePoller() - polling will stop as soon as window is closed or promise is resolved. The promise should only reject one time.
- add test for popup block case
- add test for popup timeout 
Fixes: https://github.com/okta/okta-auth-js/issues/221

Fix for popup blocker

---

package.json
packages/okta-auth-js/jest.browser.js
packages/okta-auth-js/jest.server.js
packages/okta-auth-js/karma.conf.js
packages/okta-auth-js/package.json
scripts/lint.sh
scripts/setup.sh
test/e2e/package.json
yarn.lock

- Outputs reports to the top-level `build2` directory (rather than inside `packages/okta-auth-js`)
- Avoids installing chromedriver when running only unit tests on bacon

Fix lint and unit tests on bacon

---

packages/okta-auth-js/jest.server.js
packages/okta-auth-js/lib/browser/browser.js
packages/okta-auth-js/lib/constants.js
packages/okta-auth-js/lib/server/server.js

- removes SDK_VERSION from the set of "constants"
- for browser bundle, use a global variable set by webpack
- for server entry, read from package json

fix: SDK_VERSION for server

---

README.md
packages/okta-auth-js/lib/browser/browser.js
packages/okta-auth-js/test/spec/browser.js
packages/okta-auth-js/test/spec/features.js

- Check for TextEncoder
- Provider more specific error messages

fix: PKCE isSupported method

---

README.md
package.json
packages/okta-auth-js/lib/browser/browser.js
packages/okta-auth-js/lib/oauthUtil.js
packages/okta-auth-js/lib/token.js
packages/okta-auth-js/lib/util.js
packages/okta-auth-js/test/spec/browser.js
packages/okta-auth-js/test/spec/oauthUtil.js
packages/okta-auth-js/test/spec/session.js
packages/okta-auth-js/test/spec/token.js
test/app/src/testApp.js
test/e2e/pageobjects/OktaHome.js
test/e2e/pageobjects/TestApp.js
test/e2e/specs/logout.js
test/e2e/specs/tokens.js
test/e2e/util/browserUtils.js
test/support/oauthUtil.js

- Current behavior is preserved with default options
- Passing a `postLogoutRedirectUri` will use post logout redirect flow
- Automatically reads idToken from TokenManager
- Can manually specify idToken for advanced/custom scenarios
- If `postLogoutRedirectUri` is specified, redirect logic will happen even if idToken is not available
- Clears TokenManager on signOut. All OIDC sdks have been doing this step before calling signOut. The server-side redirect method requires an idToken, so the TokenManager should not be cleared before calling signOut(). The call to `tokenManager.clear()` can be removed from the SDKs once they are using this version.

signOut: clear TokenManager and provide options for revoke and redirect

---

CHANGELOG.md
README.md
packages/okta-auth-js/lib/TokenManager.js
packages/okta-auth-js/lib/browser/browser.js
packages/okta-auth-js/package.json
packages/okta-auth-js/test/spec/browser.js
packages/okta-auth-js/test/spec/tokenManager.js
test/app/src/testApp.js
test/e2e/pageobjects/TestApp.js
test/e2e/specs/tokens.js
test/support/util.js

- top-level sdk instance will listen to error events from token manager:
- error handling for "login_required" error with accessToken will call method `onSessionExpired` if passed in options

Add "onSessionExpired" option

---

packages/okta-auth-js/lib/browser/browserStorage.js
packages/okta-auth-js/lib/token.js
packages/okta-auth-js/test/spec/cookies.js
packages/okta-auth-js/test/spec/oauthUtil.js
packages/okta-auth-js/test/spec/token.js
packages/okta-auth-js/test/spec/tokenManager.js
test/app/public/oidc-app.css
test/app/src/config.js
test/app/src/form.js
test/app/src/testApp.js
test/app/src/webpackEntry.js

- will set a 'SameSite' value on all cookies set by this SDK. Currently, these are: `okta-oauth-nonce`, `okta-oauth-state` `okta-oauth-redirect-params`, and `okta-oauth-token` (only if using tokenManager.storage = "cookie")
`okta-oauth-nonce` and `okta-oauth-state` are intended to be accessed server-side. These cookies will be set with "SameSite: Lax"
All other cookies set by the SDK are meant to be accessed client-side using Javascript. The "SameSite" setting is set to "Strict" for these. (`okta-oauth-redirect-params`, and `okta-oauth-token`)
- Updates the E2E test harness application to include settings related to cookies. This is to facilitate manual testing.

Set 'SameSite' on cookies

---

.eslintrc.json
.travis.yml
CHANGELOG.md
README.md
THIRD-PARTY-NOTICES
packages/okta-auth-js/.eslintrc.json
packages/okta-auth-js/lib/TokenManager.js
packages/okta-auth-js/lib/browser/browser.js
packages/okta-auth-js/lib/http.js
packages/okta-auth-js/lib/session.js
packages/okta-auth-js/lib/token.js
packages/okta-auth-js/lib/tx.js
packages/okta-auth-js/lib/util.js
packages/okta-auth-js/package.json
packages/okta-auth-js/test/spec/fetch-request.js
packages/okta-auth-js/test/spec/general.js
packages/okta-auth-js/test/spec/mfa-challenge.js
packages/okta-auth-js/test/spec/mfa-enroll-activate.js
packages/okta-auth-js/test/spec/mfa-required.js
packages/okta-auth-js/test/spec/pkce.js
packages/okta-auth-js/test/spec/session.js
packages/okta-auth-js/test/spec/token.js
packages/okta-auth-js/test/spec/tokenManager.js
packages/okta-auth-js/webpack.config.js
test/support/oauthUtil.js
test/support/util.js
yarn.lock

- support for promise.finally was added in Node v10.3. This matches the Active LTS version of Node: https://nodejs.org/en/about/releases/ 
Updating our "engines" and .travis file to match.

chore : remove Q, replace with standard Promise

---

CHANGELOG.md
README.md
packages/okta-auth-js/.babelrc
packages/okta-auth-js/lib/browser/browser.js
packages/okta-auth-js/package.json
packages/okta-auth-js/test/spec/browser.js
packages/okta-auth-js/webpack.common.config.js
test/app/src/config.js
test/app/src/form.js
test/app/src/testApp.js
test/e2e/pageobjects/TestApp.js
test/e2e/specs/login.js
test/e2e/specs/logout.js
test/e2e/specs/tokens.js
yarn.lock

- new method `closeSession` for XHR signout
- new method `revokeAccessToken`
- `signout` will use redirect method by default, fallback to XHR if no idToken
- `postLogoutRedirectUri` will default to `window.location.origin`

feat: signOut uses redirect method. new method closeSession

---

test/app/package.json
test/app/src/config.js
test/app/src/webpackEntry.js
yarn.lock

Adds a polyfill/shim for `TextEncoder` to the test app. This unbreaks PKCE flow in IE edge.

test app: support IE edge

---

test/app/env.js
test/app/package.json
test/app/public/index.html
test/app/public/server/index.html
test/app/server.js
test/app/src/util.js
test/app/webpack.config.js
test/e2e/pageobjects/TestServer.js
test/e2e/specs/server.js
yarn.lock

Previously we had no E2E testing of our server-side authentication flow. This adds a couple of basic tests.

test: add E2E test for server-side login

---

CHANGELOG.md
README.md
packages/okta-auth-js/lib/browser/browser.js
packages/okta-auth-js/lib/builderUtil.js
packages/okta-auth-js/lib/http.js
packages/okta-auth-js/lib/oauthUtil.js
packages/okta-auth-js/lib/server/server.js
packages/okta-auth-js/lib/session.js
packages/okta-auth-js/lib/token.js
packages/okta-auth-js/lib/tx.js
packages/okta-auth-js/test/spec/browser.js
packages/okta-auth-js/test/spec/errors.js
packages/okta-auth-js/test/spec/features.js
packages/okta-auth-js/test/spec/fingerprint.js
packages/okta-auth-js/test/spec/oauthUtil.js
packages/okta-auth-js/test/spec/pkce.js
packages/okta-auth-js/test/spec/session.js
packages/okta-auth-js/test/spec/token.js
test/support/oauthUtil.js
test/support/util.js

- issuer is now a required option
- option 'url' is deprecated and no longer used

change: deprecate options.url, enforce options.issuer

---

CHANGELOG.md
README.md
packages/okta-auth-js/lib/TokenManager.js
packages/okta-auth-js/lib/token.js
packages/okta-auth-js/test/spec/token.js
test/app/src/testApp.js
test/app/src/tokens.js
test/app/src/webpackEntry.js
test/support/oauthUtil.js
test/support/tokens.js

Changes behavior on `parseFromUrl`
Previously:
- tokens were returned in an array, in the same order as specified in `responseTypes`
- If `responseTypes` was not an array, the token object was returned
Now:
- An object is always returned. It will contain two properties
- `state` which contains the value passed to `getWithRedirect` (or any of the other `getToken` calls) This allows passing information to the callback handler.
- `tokens` which contains a hash of tokens returned. Possible key values are `idToken` and `accessToken`
- Token objects have a field `value` which contains the raw token string. For an ID token this is the same as the `idToken` field, for an access token it is the same as the `accessToken` field.

feat: parseFromUrl return tokens in hash, also include state

---

CHANGELOG.md
README.md
packages/okta-auth-js/jest.server.js
packages/okta-auth-js/lib/TokenManager.js
packages/okta-auth-js/lib/browser/browser.js
packages/okta-auth-js/lib/browser/browserStorage.js
packages/okta-auth-js/lib/http.js
packages/okta-auth-js/lib/oauthUtil.js
packages/okta-auth-js/lib/pkce.js
packages/okta-auth-js/lib/storageBuilder.js
packages/okta-auth-js/lib/token.js
packages/okta-auth-js/test/karma/spec/loginFlow.js
packages/okta-auth-js/test/karma/spec/renewToken.js
packages/okta-auth-js/test/spec/browser.js
packages/okta-auth-js/test/spec/browserStorage.js
packages/okta-auth-js/test/spec/cookies.js
packages/okta-auth-js/test/spec/oauthUtil.js
packages/okta-auth-js/test/spec/storageBuilder.js
packages/okta-auth-js/test/spec/token.js
packages/okta-auth-js/test/spec/tokenManager.js
test/app/src/config.js
test/app/src/form.js
test/support/util.js

- secure cookies are turned on by default
- HTTP origin other than localhost will throw, unless secureCookies is set to false
- config option `tokenManager.secure` is deprecated. TokenManager will use `secureCookies` SDK setting

feat: enable secure cookies by default, enforce HTTPS origin

---

CHANGELOG.md
README.md
packages/okta-auth-js/lib/crypto.js
packages/okta-auth-js/lib/token.js
packages/okta-auth-js/test/karma/spec/crypto.js
packages/okta-auth-js/test/spec/token.js
test/app/server.js
test/app/src/config.js
test/app/src/form.js
test/app/src/testApp.js
test/app/src/tokens.js
test/e2e/pageobjects/TestApp.js
test/e2e/specs/tokens.js
test/e2e/util/appUtils.js
test/support/oauthUtil.js

- default `responseType` is now ['token', 'id_token'] (when using implicit flow. PKCE always requests both tokens)
- when both access token and id token are returned the id token's `at_hash` claim will be validated against the access token
- modifies test app to be handle cases where only 1 token is requested

feat: validate idToken.claims.at_hash against access token

---

CHANGELOG.md
README.md
packages/okta-auth-js/lib/browser/browser.js
packages/okta-auth-js/lib/oauthUtil.js
packages/okta-auth-js/lib/token.js
packages/okta-auth-js/package.json
packages/okta-auth-js/test/spec/token.js
test/app/src/config.js
test/app/src/form.js
test/e2e/pageobjects/TestApp.js
test/e2e/specs/login.js
test/e2e/util/appUtils.js
test/e2e/util/loginUtils.js
test/support/oauthUtil.js

- adds support for `responseMode="query"` if using PKCE flow (server returns an unsupported response mode error if using implicit flow)
- option can be passed either in SDK constructor or as an option to `getWithRedirect` and `parseFromUrl`

feat: support responseMode=query for PKCE flow

---

README.md
packages/okta-auth-js/lib/token.js
packages/okta-auth-js/test/spec/token.js
test/support/util.js

- checks the "sub" returned in the `/userinfo` response against the idToken claim. (This is to mitigate potential man-in-the-middle token substitution attacks)
- call now requires both an access token object and an ID token object
- parameters are optional; tokens will be read from TokenManager if not passed.

change: getUserInfo requires idToken, will read from TokenManager

---

README.md
packages/okta-auth-js/lib/token.js
packages/okta-auth-js/test/karma/spec/loginFlow.js
packages/okta-auth-js/test/spec/token.js
test/e2e/pageobjects/TestApp.js
test/e2e/specs/login.js
test/e2e/util/loginUtils.js
test/support/oauthUtil.js

- responseMode will not be passed to authorize endpoint unless explicitly specified
- default responseMode for PKCE is "query"

feat: responseMode uses openid defaults

---

CHANGELOG.md
packages/okta-auth-js/lib/fetch/fetchRequest.js
packages/okta-auth-js/test/spec/fetch-request.js

- Catch error from json parsing caused by invalid/malformed server response and return a well structured error rather than the raw TypeError. SIW has unit tests for these scenarios. Adding tests here to cover the same functionality.
- Always return `responseText` as a string. SIW had unit tests which revealed this quirk/bug in this library. If response type is JSON, the object will also be returned as `responseJSON` and `responseType` will be set to JSON.

fix: fetch: handle invalid server responses, set responseType

---

packages/okta-auth-js/jest.server.js
packages/okta-auth-js/lib/browser/browserStorage.js
packages/okta-auth-js/lib/token.js
packages/okta-auth-js/test/spec/.eslintrc.json
packages/okta-auth-js/test/spec/browser.js
packages/okta-auth-js/test/spec/browserStorage.js
packages/okta-auth-js/test/spec/oauthUtil.js
packages/okta-auth-js/test/spec/session.js
packages/okta-auth-js/test/spec/token.js
packages/okta-auth-js/test/spec/tokenManager.js

Fixes issue with Chrome 80: https://blog.chromium.org/2020/02/samesite-cookie-changes-in-february.html
The main effect is that running within an iFrame is now only supported if the app is being hosted on a HTTPS protocol.
- OAuth redirect and PKCE cookies will default to `SameSite:Lax`, unless running on HTTPS protocol, then cookies will use `SameSite: None; Secure`
- HTTP cache will use `SameSite: Lax` unless running on HTTPS protocol, then cookies will use `SameSite: None; Secure`
- TokenManager (if falling back to using cookie storage) will use `SameSite: Lax` unless the `secure` option is set to true, then it will use `SameSite: None; Secure`
TokenManager is preserving existing opt-in behavior to avoid a breaking change. The scenario is that some customers may have an app running on …

fix: sameSite: use "lax" on HTTP

---

packages/okta-auth-js/lib/token.js
packages/okta-auth-js/test/spec/token.js
test/support/oauthUtil.js

This is a fix for non-SPA applications, using authorization_code flow. Generally these apps will process the code server-side and so will not need to call `parseFromUrl`, but if they do they will receive an error. This fixes the logic so the code will not be exchanged for a token if pkce=false. The code will be returned.

fix: responseType=code: return code, support pkce=false

---

CHANGELOG.md
README.md
packages/okta-auth-js/lib/browser/browser.js
packages/okta-auth-js/lib/builderUtil.js
packages/okta-auth-js/lib/server/server.js
packages/okta-auth-js/package.json
packages/okta-auth-js/test/spec/builderUtil.js
test/app/src/testApp.js

Expose server bundle for React Native platform as an Authentication SDK.

chore: use server bundle for react native

---

CHANGELOG.md
packages/okta-auth-js/lib/browser/browser.js
packages/okta-auth-js/lib/token.js
packages/okta-auth-js/package.json
packages/okta-auth-js/test/spec/browser.js
packages/okta-auth-js/test/spec/features.js
packages/okta-auth-js/test/spec/pkce.js
yarn.lock

- Will reject with error if PKCE is enabled but not supported when OIDC flow is initiated. Previously this check was done in the constructor and affected non-OIDC flows
- Will print a console warning and disable secure cookies if cookies.secure is enabled on an HTTP connection. Previously this would throw in the constructor.
Related issues:
OKTA-291890
OKTA-291889

fix: assert PKCE only for OIDC flows. Warn for insecure cookies

---

packages/okta-auth-js/lib/browser/browser.js
packages/okta-auth-js/lib/builderUtil.js
packages/okta-auth-js/lib/server/server.js
packages/okta-auth-js/test/spec/builderUtil.js
packages/okta-auth-js/test/spec/fingerprint.js
packages/okta-auth-js/test/spec/general.js
packages/okta-auth-js/test/spec/pkce.js
packages/okta-auth-js/test/spec/token.js

corrects user agent. It will be:
`okta-auth-js/version` for browser code
`okta-auth-js-server/version` for server code
custom template will include the default user agent (browser or server)

fix: user agent

---

packages/okta-auth-js/lib/browser/browserStorage.js
packages/okta-auth-js/lib/pkce.js
packages/okta-auth-js/test/spec/browserStorage.js
packages/okta-auth-js/test/spec/pkce.js

This fixes an error involving PKCE flow and the signin widget. In version 3.1.2 of `okta-auth-js` the PKCE meta storage was changed to use sessionStorage. However, current and older versions of the signin widget which are bundled with an older version of `okta-auth-js` will store the PKCE meta in local storage. This will cause an error: **The redirectUri passed to /authorize must also be passed to /token** on callback. The underlying cause is that PKCE meta was not found in storage and an empty codeVerifier was passed to the `/token` endpoint.
This PR adds logic to read from local storage if the meta cannot be found in session storage. This will provide compatibility for older versions of `okta-auth-js` including the bundled version within the signin widget.
Additionally, this PR adds …

compat fix: PKCE loadMeta will fallback to local storage

---

CHANGELOG.md
packages/okta-auth-js/lib/token.js
test/app/src/config.js
test/app/src/form.js
test/app/src/testApp.js

See related GH issue: https://github.com/okta/okta-auth-js/issues/396
Currently the SDK assumes that PKCE flow will always be used for obtaining both an idToken and an accessToken. This PR unbreaks that assumption and allows an accessToken to be retrieved without an idToken. This also allows retrieving "default" scopes as defined by the custom authorization server

Support retrieving an accessToken only, with default scopes

---

CHANGELOG.md
README.md
packages/okta-auth-js/lib/TokenManager.js
packages/okta-auth-js/lib/browser/browser.js
packages/okta-auth-js/lib/oauthUtil.js
packages/okta-auth-js/lib/token.js
packages/okta-auth-js/test/spec/oauthUtil.js
packages/okta-auth-js/test/spec/pkce.js
packages/okta-auth-js/test/spec/token.js
packages/okta-auth-js/test/spec/tokenManager.js

Changes: 
1. add `isOAuthCallback` function in oauthUtil module
2. guard token.get* (different getToken methods) with isOAuthCallback
3. guard tokeManager.get with isOAuthCallback (if autoRenew is on)
4. add unit tests
5. add error handling examples in README

feat: add isAuthCallback util and setup validations based on it - OKTA-285863

---

packages/okta-auth-js/lib/browser/browser.js
packages/okta-auth-js/test/spec/fingerprint.js

Based on https://github.com/okta/okta-core/blob/master/webapp/src/main/resources/META-INF/resources/WEB-INF/jsp/auth/device-fingerprint.jsp, the message listener only should expect parsable JSON strings.
This PR can be a short-term fix, a more robust fix can be adding prefix or namespace flag to messages that originated from OKTA.

fix: fingerprint iframe message - OKTA-314036

---

CHANGELOG.md
packages/okta-auth-js/lib/pkce.js
packages/okta-auth-js/lib/token.js
packages/okta-auth-js/test/spec/pkce.js
test/app/public/index.html
test/app/public/oidc-app.css
test/app/src/testApp.js
test/app/src/webpackEntry.js

This PR fixes an issue involving PKCE metadata:
- current version of the widget stores PKCE code in localStorage
- current version of authJS looks for code in sessionStorage, but falls back to localStorage if code is not present
- token renew failure does not cleanup but leaves a code in sessionStorage. token renew failure can occur if the session is expired OR if 3rd party cookies are blocked
- the error occurs because the code from token renew (in sessionStorage) is passed to the /token endpoint instead of the code saved from the widget (in localStorage)
This PR fixes the issue by favoring localStorage over sessionStorage in `loadMeta`. If meta exists in both locations, we will use the value in localStorage because it is assumed the meta was put there by an older version of the signin …

fix: clear PKCE meta before save. favor localSession when reading meta.

---

CHANGELOG.md
packages/okta-auth-js/lib/browser/browser.js
packages/okta-auth-js/test/spec/browser.js
test/app/src/config.js

Fixes:
- by default to redirect to `window.location.origin` in signOut when users session already expired. This will fix an issue when user already in a secure route (in SPA, like `/profile`), signOut should redirect user to `window.location.origin` instead of reload the `/profile` route.
(Edit by @aarongranick-okta ): This logic only occurs if `idToken` is missing during signOut. User will be redirected to origin or `postLogoutRedirectUri` after the XHR signOut method is used. If the postLogoutRedirectUri matches the current URI, the page will be reloaded to match the logic of a full redirect.

fix: signout session already expired scenario

---

CHANGELOG.md
README.md
lib/TokenManager.ts
lib/browser/browser.ts
lib/types/OktaAuthOptions.ts
test/app/src/testApp.ts
test/e2e/specs/tokens.js
test/spec/browser.js
test/spec/token.js
test/spec/tokenManager.js
test/support/oauthUtil.js

- remove `onSessionExpired`
- implement active autoRenew
- remove renew logic from `tokenManager.get()`
- adds `tokenManager.hasExpired(token)` to test if a token is expired or not.

breaking changes for 4.0

---

scripts/unit.sh

Apparently chrome setup exits with non zero code. Rewriting unit.sh to check error code on build

fixes unit on bacon

---

jest.browser.js
lib/TokenManager.ts
test/spec/tokenManager.js
test/support/nodeExceptions.js
test/support/oauthUtil.js
test/support/util.js

- adds unhandled promise rejection handler which will cause test to fail if there is an unhandled promise rejection after the test is complete
- will fail test if PromiseQueue is not empty at the end of the test
- sets autoRenew to false by default within tests
- tokenManager will clear() after each test involving autoRenew (to clear timeouts)

fixes flakey tests related to autoRenew

---

CHANGELOG.md
README.md
lib/TokenManager.ts
test/spec/tokenManager.js

related issue: https://github.com/okta/okta-oidc-js/issues/894

fix: add rate limiting logic to autoRenew

---

packages/okta-auth-js/lib/browser/browser.js
packages/okta-auth-js/test/spec/browser.js

sameSite cookie settings were being set incorrectly on HTTP connections unless `secure=false` was set. This fixes the issue so secure=false and sameSite=lax are automatically selected when running on HTTP. Logic involving localhost has been removed.
Related issue: OKTA-323826
**This PR is based on 3.2 branch and will be released as a patch update**

fix sameSite cookie settings on HTTP

---

packages/okta-auth-js/lib/token.js
test/app/src/testApp.js
test/app/src/webpackEntry.js
test/e2e/pageobjects/TestApp.js
test/e2e/specs/login.js
test/e2e/util/loginUtils.js

- maintains compatibility with older widget / authJS versions by reading from cookie before sessionStorage
- adds E2E tests for siginin widget (problem was reproduced using this test before fix was added)
This PR is for 3.2 branch. Change will be cherry-picked and added to a PR for 4.0 branch

fixes issue with oauth params cookie

---

CHANGELOG.md
README.md
lib/AuthStateManager.ts
lib/OktaAuthBase.ts
lib/browser/browser.ts
lib/server/server.ts
lib/types/OktaAuthOptions.ts
lib/types/api.ts
lib/util.ts
test/karma/spec/renewToken.js
test/spec/AuthStateManager.js
test/spec/browser.js
test/spec/tokenManager.js
test/spec/util.js

This PR changes public methods based on `dev-4.1`, the changes include:
- keeps `signIn` for signIn with credential only, and mark this method with deprecate soon.
- adds new alias method `signInWithCredential` as future replacement of `signIn`
- adds new method `signInWithRedirect` for browser redirect signIn flow
- removes `onAuthRequired` callback as there is no callback logic for it in authJs internal flow, move to downstream SDKs to handle
- removes `setFromUri` and `getFromUri` and internal relative <-> absolute uri transform logic, since without proper baseUri, the logic is error prone, users should be able to get whatever they set.
- removes and resolves `fromUri` (if has been set) in `handleAuthentication`

refactor browser public methods

---

CHANGELOG.md
lib/browser/browser.ts
lib/util.ts
test/spec/util.js

resolves: https://github.com/okta/okta-vue/issues/19

feat: support relative redirect uri - OKTA-324356

---

CHANGELOG.md
lib/token.ts
test/spec/token.js
test/support/oauthUtil.js
test/support/util.js

Also need to cherry-pick this change to 3.2.x

fix: oauth redirect params legacy browsers support issue - OKTA-337243

---

lib/oauthUtil.ts
test/spec/oauthUtil.js
test/spec/token.js

Changes:
- in `token.isLoginRedirect()` check not only presence of parameter `code` in query/hash, but current location URI should be allowed redirect URI
Thus SDK will not false handle any routes with `code` parameter as redirect route.
Resolves: https://github.com/okta/okta-auth-js/issues/474
Internal ref: https://oktainc.atlassian.net/browse/OKTA-331632

Check redirect URI in token.isLoginRedirect()

---

.gitignore
packages/okta-auth-js/lib/token.js
packages/okta-auth-js/test/spec/.eslintrc.json
packages/okta-auth-js/test/spec/token.js
test/e2e/package.json
test/support/oauthUtil.js
test/support/util.js
yarn.lock

Write: add OAuth params into both sessionStorage and cookies
Read: favor cookies first, then try sessionStorage to compatible with old versions of SIW.
https://github.com/okta/okta-auth-js/pull/514#issuecomment-712494247

Sw fix oauth params 3.x

---

CHANGELOG.md
README.md
lib/browser/browser.ts
lib/browser/index.ts
lib/util.ts
test/spec/browser.js
test/spec/util.js

Changes:
* adds `sdk.isAuthenticated` to resolve with non-pending `isAuthenticated` state
* changes `sdk.getAccessToken` and `getIdToken` to read from in-memory authState
* provides tokens to `sdk.getUser` from in-memory authState
* add `util.toRelativeUrl`

feat: add methods for v4.1 - OKTA-340176

---

CHANGELOG.md
lib/token.ts
lib/types/Token.ts
test/support/oauthUtil.js
test/support/tokens.js

As this PR changes the token type, it still looks like a breaking change.

feat: remove value field from token - OKTA-338251

---

CHANGELOG.md
README.md
lib/browser/browser.ts
lib/token.ts
test/spec/browser.js

https://oktainc.atlassian.net/browse/OKTA-340725

accept responseType as a constructor arg

---

lib/browser/browser.ts
lib/token.ts
test/spec/browser.js

A bug in `getDefaultTokenParams` was preventing scopes set in the constructor from being honored.
Also cleans up/refactors the code a little bit, removes unnecessary override of `responseType` in `signInWithRedirect`

fix: respect scopes set in constructor

---

samples/test/features/self-service-registration.feature
samples/test/support/management-api/upsertPolicyRule.ts
scripts/e2e-express-embedded-sign-in-widget.sh
scripts/e2e-express-web-no-oidc.sh
scripts/e2e-express-web-with-oidc.sh
scripts/e2e-react-embedded-auth-with-sdk.sh
scripts/e2e-static-spa.sh
scripts/e2e-webpack-spa.sh
scripts/e2e.sh

- Changed the error message check to be generic in SSR test
- A new change going into okta-core will disable email and phone authenticators in policies unless enabled through admin console. Made a change in policy json to disable this constraint
- Generic script clean up

Updates error message to be generic

---

CHANGELOG.md
lib/idx/remediators/GenericRemediator/GenericRemediator.ts
package.json
samples/test/features/self-service-registration.feature
samples/test/support/management-api/upsertPolicyRule.ts
scripts/e2e-express-embedded-sign-in-widget.sh
scripts/e2e-express-web-no-oidc.sh
scripts/e2e-express-web-with-oidc.sh
scripts/e2e-react-embedded-auth-with-sdk.sh
scripts/e2e-static-spa.sh
scripts/e2e-webpack-spa.sh
scripts/e2e.sh
test/spec/idx/remediators/GenericRemediator.ts

Only allow to proceed when options.step is specifically provided from downstream clients, so unneeded auto proceeding can be avoid.

fix(idx:useGenericRemediator): decide canRemediate based on step in options (beta)

---

CHANGELOG.md
lib/idx/util.ts
test/spec/idx/util.ts

Issue:
The following error happens when `idx.session.expired` error happen. It's because generic remediator will always be available and it runs `getNextStep` fn even it's a terminal error.
```
message: "Cannot read properties of undefined (reading 'name')"
stack: "TypeError: Cannot read properties of undefined (reading 'name')
at GenericRemediator.getName (http://localhost:3000/okta-sign-in.next.js:218334:31)
at GenericRemediator.getNextStep (http://localhost:3000/okta-sign-in.next.js:219412:23)
at getNextStep (http://localhost:3000/okta-sign-in.next.js:221990:29)
at handleIdxError (http://localhost:3000/okta-sign-in.next.js:222013:32)
at _loop$ (http://localhost:3000/okta-sign-in.next.js:217624:53)
at tryCatch (http://localhost:3000/okta-sign-in.next.js:268845:17)
at Generator.invoke …
```

fix: generic remediator error handling issue

---

CHANGELOG.md
lib/util/url.ts
test/spec/util.js

Changes to `isAbsoluteUrl` util according to [RFC2396](https://www.ietf.org/rfc/rfc2396.txt):
- Support custom URL scheme 
- Don't treat network-path (URL starts with '//') as absolute URL
Resolves https://github.com/okta/okta-auth-js/issues/1248 and https://github.com/okta/okta-oidc-android/issues/219
Internal ref: https://oktainc.atlassian.net/browse/OKTA-511508

Allow custom scheme in `isAbsoluteUrl`

---

samples/test/features/account-unlock.feature
samples/test/steps/then.ts

- Account unlock test failing on trex due to message change in backend
- Updates the test to check if message contains `unlocked` instead of specific error message

Updates account unlock error message

---

.bacon.yml
.eslintrc.js
.travis.yml
babel.cjs.js
package.json
samples/generated/express-embedded-auth-with-sdk/package.json
samples/generated/express-embedded-sign-in-widget/package.json
samples/templates/express-embedded-sign-in-widget/package.json
samples/test/package.json
samples/test/steps/when.ts
samples/test/support/management-api/createCredentials.ts
scripts/setup.sh
scripts/travis.sh
test/support/package.json
test/types/authStateManager.test-d.ts
yarn.lock

- Set min supported Node version to 14
- Update `broadcast-channel` to `^4.14.0` (latest version depends on `microtime 3.1.0` which requires Node 14)
- Don't use `corejs: 3` in `@babel/plugin-transform-runtime` (was needed for `Object.fromEntries` which requires Node 12)
- `microtime` is a native module, needs to be built manually in Bacon setup script because of `--ignore-scripts` flag
Internal ref: [OKTA-504784](https://oktainc.atlassian.net/browse/OKTA-504784)
Fixes https://github.com/okta/okta-auth-js/issues/1256

Upgrade minimal node support version to 14

---

README.md
lib/oidc/endpoints/authorize.ts
lib/oidc/exchangeCodeForTokens.ts
lib/oidc/handleOAuthResponse.ts
lib/oidc/options/OAuthOptionsConstructor.ts
lib/oidc/types/UserClaims.ts
lib/oidc/types/api.ts
lib/oidc/types/meta.ts
lib/oidc/types/options.ts
lib/oidc/types/proto.ts
lib/oidc/util/defaultTokenParams.ts
lib/oidc/util/oauthMeta.ts
lib/oidc/util/validateClaims.ts
lib/oidc/verifyToken.ts
test/apps/app/src/config.ts
test/apps/app/src/form.ts
test/apps/app/src/testApp.ts
test/e2e/specs/login.js
test/spec/oidc/endpoints/authorize.ts
test/spec/oidc/exchangeCodeForTokens.ts
test/spec/oidc/util/defaultTokenParams.ts
test/spec/oidc/util/oauthMeta.ts
test/spec/oidc/util/validateClaims.ts

- Adds support of `acr_values` in `authorize` endpoint
- Validate token claim `acr` against `acr_values`
- Added unit tests
- Added support of `acr_values` in test app
Internal ref: [OKTA-535359](https://oktainc.atlassian.net/browse/OKTA-535359)
[Docs](https://developer.okta.com/docs/guides/step-up-authentication/main/)

feat: support acr_values for authorize endpoint

---

docs/myaccount/README.md
lib/myaccount/README.md
lib/myaccount/request.ts
samples/generated/react-embedded-auth-with-sdk/src/components/Profile/Main.jsx
samples/generated/react-embedded-auth-with-sdk/src/components/WidgetPage.jsx
test/spec/myaccount/request.ts

- Handle `acr_values` in `insufficient_authentication_context` error (same as `max_age`), added unit test
- Support `acrValues` in MyAccount React sample app
TODO: wait for feature availability on backend and check sample app
Internal ref: https://oktainc.atlassian.net/browse/OKTA-535363

feat: Handle acr_values from insufficient_authentication_context error

---

lib/http/request.ts
lib/myaccount/request.ts
test/spec/http/request.ts
test/spec/myaccount/request.ts

Move `insufficient_authentication_context` error handling logic from myaccount http level to core http level
Internal ref: https://oktainc.atlassian.net/browse/OKTA-535363

Move `insufficient_authentication_context` error handling logic to core http

---

package.json
polyfill/index.js
test/apps/app/README.md
test/apps/app/webpack.config.js
webpack.polyfill.config.js
yarn.lock

OKTA-539015
* replace `text-encoding` with `fast-text-encoding`
* add missing polyfills for IE11
* check polyfill bundle size

chore: check polyfill bundle size

---

CHANGELOG.md
lib/idx/register.ts
test/spec/idx/register.ts

Issue: https://oktainc.atlassian.net/browse/OKTA-548934

fix: Don't check for 'identify' remediation if 'activationToken' is used

---

CHANGELOG.md
README.md
docs/myaccount/interfaces/OktaAuthMyAccountInterface.md
lib/oidc/mixin/index.ts
lib/oidc/types/api.ts
lib/session/mixin.ts
lib/session/types.ts
samples/config.js
test/spec/OktaAuth/api.ts
test/spec/OktaAuth/browser.ts
test/types/auth.test-d.ts

Change to [closeSession](https://github.com/okta/okta-auth-js#closesession): Now returns a promise that resolves with `true` if an existing Okta session have been closed, or `false` if a session does not exist or has already been closed. 
Also applies to [signOut](https://github.com/okta/okta-auth-js#signout) - resolves with the result of `closeSession` (if a fallback to closeSession is used) or `true` in other cases.
Resolves #1394
Internal ref: [OKTA-594167](https://oktainc.atlassian.net/browse/OKTA-594167)

Change return type for `closeSession` and `signOut` to `Promise<boolean>`

---

lib/services/AutoRenewService.ts
lib/services/LeaderElectionService.ts
lib/services/SyncStorageService.ts
samples/test/features/embedded-widget-basic-auth.feature
test/spec/services/AutoRenewService.ts
test/spec/services/LeaderElectionService.ts
test/spec/services/SyncStorageService.ts

Resolves issue https://github.com/okta/okta-auth-js/issues/1164
Internal ref: OKTA-597615
If `start` is called 2 times concurrently for single `OktaAuth` instance (and thus for `LeaderElectionService`), 2 instances of `LeaderElector` can be created:
https://github.com/okta/okta-auth-js/blob/master/lib/services/LeaderElectionService.ts#L59
One 1 of 2 electors can become leader.
But only last one will be assigned to `this.elector` an used in method [`isLeader()`](https://github.com/okta/okta-auth-js/blob/master/lib/services/LeaderElectionService.ts#L47)
If an "orphan" elector (not assigned to `this.elector`) becomes a leader, it causes the issue #1164 because `isLeader()` will return false

Fix race condition in LeaderElectionService start

---

CHANGELOG.md
package.json
scripts/buildtools/build.js

This resolves issue https://github.com/okta/okta-auth-js/issues/1393 when `fetch` does not work with `@okta//okta-react-native` (Error `fetch is not a function`)
By default React Native uses `browser` key in `package.json` of okta-auth-js which is `UMD` build made with Webpack.
Adding special `react-native` key in `package.json` helps resolving okta-auth-js with `ESM` browser build which has no fetch polyfill and works correctly.
Internal ref: https://oktainc.atlassian.net/browse/OKTA-592572

Add `react-native` to `package.json`

---

package.json
scripts/integration.sh
scripts/setup-e2e.sh
scripts/setup.sh
yarn.lock

* Re-resolve `decode-uri-component` version to latest semver
* Forcefully resolve `http-cache-semantics` to `^4.0.0`
* Migrate secrets to Vault

Upgrades `decode-uri-component`, `http-cache-semantics` to latest

---

.bacon.yml
samples/generated/react-embedded-auth-with-sdk/package.json
samples/generated/react-embedded-auth-with-sdk/src/components/WidgetPage.jsx
scripts/setup.sh
scripts/utils/install-beta-pkg.sh
scripts/utils/siw-platform-scripts.sh
scripts/verify-registry-install.sh
yarn.lock

- Use `siw-platform-scripts` to install SIW instead of artifactory url
- Increased timeouts for Bacon tasks
- Upgraded `@okta/okta-signin-widget` from v6 to v7 in sample `react-embedded-auth-with-sdk`
Internal ref: [OKTA-607419](https://oktainc.atlassian.net/browse/OKTA-607419)

Use siw-platform-scripts instead of artifactory url

---

CHANGELOG.md
lib/idx/authenticator/util.ts
lib/idx/idxState/v1/idxResponseParser.ts
lib/idx/remediators/Base/SelectAuthenticator.ts
test/spec/idx/authenticator/util.ts
test/spec/idx/idxState/unit/v1/idxResponseParser.test.js
test/spec/idx/remediators/SelectAuthenticator.ts

If there is incorrect `relatesTo` in IDX response from server, it can lead to unexpected behaviour, so throw an error.
In [the infinite requests bug scenario](https://oktainc.atlassian.net/browse/OKTA-612326) remediation `select-authenticator-authenticate` was falsely selected instead of `challenge-authenticator`, because `canRemediate()` [returns true](https://github.com/okta/okta-auth-js/blob/master/lib/idx/remediators/Base/SelectAuthenticator.ts#L61) due to mistake in line 36:
https://github.com/okta/okta-auth-js/blob/933fff3fb15fa7348112bc51f3decd6ae48ef914/lib/idx/remediators/Base/SelectAuthenticator.ts#L36
Phone authenticator has incorrect `relatesTo: "$.authenticatorEnrollments.value[9]"`, so `relatesTo.key` is undefined and `authenticator.key` is also undefined, leading to false …

Throw error if there is incorrect `relatesTo` in IDX response

---

.bacon.yml
CHANGELOG.md
lib/idx/remediate.ts
lib/idx/remediators/Base/Remediator.ts
lib/idx/remediators/Base/SelectAuthenticator.ts
lib/idx/util.ts
package.json
samples/generated/express-embedded-auth-with-sdk/web-server/routes/authenticator.js
samples/test/features/self-service-registration-custom-attribute.feature
samples/test/features/self-service-registration.feature
samples/test/steps/when.ts
samples/test/support/action/selectAuthenticator.ts
samples/test/support/action/selectAuthenticatorMethod.ts
samples/test/support/selectors/SelectAuthenticatorMethod.ts
samples/test/support/selectors/index.ts
test/spec/idx/remediate.ts
test/spec/idx/remediators/SelectAuthenticator.ts
test/spec/idx/util.ts

Fix: Don't auto remediate `select-authenticator-authenticate`/`select-authenticator-enroll` if authenticator has been already selected (`currentAuthenticatorEnrollment`/`currentAuthenticator` is present in IDX response)
Note: `currentAuthenticator`  is used during enrollment, `currentAuthenticatorEnrollment` during verify flow. Both means the same, naming is confusing.
Internal ref: [OKTA-612939](https://oktainc.atlassian.net/browse/OKTA-612939), [OKTA-609234](https://oktainc.atlassian.net/browse/OKTA-609234)

fix: Don't auto remediate SelectAuthenticator with current authenticator

---

CHANGELOG.md
lib/oidc/factory/api.ts
lib/oidc/index.ts
lib/oidc/introspect.ts
lib/oidc/renewTokens.ts
lib/oidc/types/Token.ts
lib/oidc/types/api.ts
lib/oidc/types/options.ts
lib/oidc/types/proto.ts
test/spec/oidc/introspect.ts
test/spec/oidc/renewTokens.ts
yarn.lock

- adds ouath introspect method
- adds optional param to `renewTokens` to pass tokens in directly, avoiding requesting from TokenManager

feat: adds oauth introspect method

---

CHANGELOG.md
README.md
lib/oidc/mixin/index.ts
lib/oidc/types/api.ts
test/spec/OktaAuth/browser.ts

Resolves #1410 and #1433
- allows for `postLogoutRedirectUri` to be `null` to invoke default `/logout` redirect behavior
- returns `state` as query param to redirect uri when `.signOut` falls back to `.closeSession`

.signOut improvements

---

CHANGELOG.md
rollup.config.js

Copy of https://github.com/okta/okta-auth-js/pull/1373

fix: Fixes ESM build for Node.js

---

lib/oidc/TokenManager.ts
test/spec/TokenManager/renew.ts

- Adds missing emitting of error in `renew` function when `getSync` returns an undefined token

Emits error when TokenManager can't find token in renew

---

CHANGELOG.md
lib/oidc/util/validateClaims.ts
package.json
test/spec/oidc/util/validateClaims.ts

Per the openid spec, aud can be an array and in special cases a single string.  This fixes a bug where the array case is not handled.  This is a non breaking change.
Tests for the following scenarios:
- aud is an array but does NOT contain the clientId throws an error
- aud is an array and does contain the clientId validates with no error
Resolves: [1480](https://github.com/okta/okta-auth-js/issues/1480)

fix: Allows aud to be an array when validating claims

---

CHANGELOG.md
lib/http/request.ts
test/spec/http/request.ts

`fetch` can throw exceptions: https://developer.mozilla.org/en-US/docs/Web/API/fetch#exceptions
[formatError](https://github.com/okta/okta-auth-js/blob/master/lib/http/request.ts#L55) currently will return `AuthApiError` with `xhr` property set to `TypeError` object.
[generateIdxAction](https://github.com/okta/okta-auth-js/blob/master/lib/idx/idxState/v1/generateIdxAction.ts#L55) will try to parse `xhr` as JSON and will trigger error `SyntaxError: "undefined" is not valid JSON`
You can reproduce with SIW playground with mock [authenticator-enroll-select-authenticator-with-skip](https://github.com/okta/okta-signin-widget/blob/master/playground/mocks/data/idp/idx/authenticator-enroll-select-authenticator-with-skip.json#L173) having incorrect url `http://localhost:3000:1802/idp/idx/cancel`. …

Handle fetch exceptions

---

CHANGELOG.md
lib/idx/authenticator/Authenticator.ts
lib/idx/authenticator/OktaPassword.ts
samples/test/features/basic-auth.feature
test/spec/idx/recoverPassword.ts

Adds `revokeSessions` input value for `OktaPassword` authenticator.
Should be mapped to `credentials.revokeSessions` in IDX API request.
`revokeSessions` is an optional parameter used for `ResetAuthenticator` remediator.
Fixes issue https://github.com/okta/okta-auth-js/issues/1453
Internal ref: https://oktainc.atlassian.net/browse/OKTA-645241

Add revokeSessions for OktaPassword

---

CHANGELOG.md
lib/oidc/endpoints/token.ts
lib/oidc/exchangeCodeForTokens.ts
lib/oidc/handleOAuthResponse.ts
lib/oidc/renewToken.ts
lib/oidc/renewTokens.ts
lib/oidc/renewTokensWithRefresh.ts
lib/oidc/types/Token.ts
lib/oidc/types/meta.ts
lib/oidc/util/oauthMeta.ts
package.json
samples/test/cucumber.wdio.conf.ts
scripts/e2e/e2e-mfa.sh
scripts/e2e/e2e-saucelabs.sh
scripts/integration.sh
scripts/samples/e2e-express-embedded-auth-with-sdk-features.sh
scripts/samples/e2e-express-embedded-auth-with-sdk-spec.sh
scripts/samples/e2e-express-embedded-auth-with-sdk.sh
scripts/setup-e2e.sh
scripts/setup.sh
test/apps/app/src/testApp.ts
test/spec/oidc/endpoints/token.ts
test/spec/oidc/exchangeCodeForTokens.ts
test/spec/oidc/parseFromUrl.ts
test/spec/oidc/renewTokens.ts
test/spec/oidc/util/handleOAuthResponse.ts

Note: includes #1531 (which was merged to master)

feat: enable `extraParams` to persist to token refresh

---

lib/authn/util/link2fn.ts
lib/authn/util/poll.ts
lib/base/types.ts
lib/constants.ts
lib/features.ts
lib/http/request.ts
lib/http/types.ts
lib/idx/idxState/v1/generateIdxAction.ts
package.json
test/spec/TokenManager/browser.ts
test/spec/TokenManager/expireEvents.ts
test/spec/authn/mfa-challenge.js
test/spec/features/browser.ts
test/spec/http/request.ts
test/spec/idx/IdxStorageManager.ts
test/spec/oidc/OAuthStorageManager.ts
test/spec/oidc/endpoints/well-known.ts
test/spec/oidc/util/prepareEnrollAuthenticatorParams.ts
test/spec/oidc/util/prepareTokenParams.ts
yarn.lock

Fixes [bug in Mobile Safari 18.0-18.2](https://github.com/denysoblohin-okta/ios_fetch_bug) for poll requests.
We should wait ~500ms after document become visible before making poll requests. 
If `fetch` still failed with error `Load failed`, restart fetch request.

Fix bug in Mobile Safari 18.x: start poll request when document is visible and awaken

---

CHANGELOG.md
lib/authn/util/poll.ts
lib/base/types.ts
lib/features.ts
lib/http/request.ts
package.json
test/spec/TokenManager/browser.ts
test/spec/TokenManager/expireEvents.ts
test/spec/authn/mfa-challenge.js
test/spec/features/browser.ts
test/spec/http/request.ts
test/spec/idx/IdxStorageManager.ts
test/spec/oidc/OAuthStorageManager.ts
test/spec/oidc/endpoints/well-known.ts
test/spec/oidc/util/prepareEnrollAuthenticatorParams.ts
test/spec/oidc/util/prepareTokenParams.ts
yarn.lock

- Removed `ua-parser-js`
- Rewritten `isMobileSafari18` to `isSafari18` without using external lib
- Detecting both desktop and mobile Safari 18 because of [comment](https://github.com/okta/okta-auth-js/pull/1552#issuecomment-2575846858) and taking in account that enabling desktop mode in iOS Safari [emulates Micantosh in user agent](https://okta.slack.com/archives/C07U2SEBZC5/p1736441085869779?thread_ts=1736335973.495079&cid=C07U2SEBZC5)

Remove `ua-parser-js`. Change `isMobileSafari18` to `isSafari18`

---

CHANGELOG.md
lib/authn/util/poll.ts
lib/base/types.ts
lib/constants.ts
lib/features.ts
lib/http/options.ts
lib/http/request.ts
lib/http/types.ts
test/spec/OktaAuth/constructor.ts
test/spec/TokenManager/browser.ts
test/spec/TokenManager/expireEvents.ts
test/spec/authn/mfa-challenge.js
test/spec/features/browser.ts
test/spec/http/request.ts
test/spec/idx/IdxStorageManager.ts
test/spec/oidc/OAuthStorageManager.ts
test/spec/oidc/endpoints/well-known.ts
test/spec/oidc/util/prepareEnrollAuthenticatorParams.ts
test/spec/oidc/util/prepareTokenParams.ts
test/types/authn.mixin.test-d.ts
test/types/config.test-d.ts
test/types/idx.mixin.test-d.ts
test/types/mixin.test-d.ts

- Remove util `isSafari18` introduced in https://github.com/okta/okta-auth-js/pull/1552 and https://github.com/okta/okta-auth-js/pull/1562
- Add SDK option `pollDelay` to enable polling fix logic (recommended value: 500)
Issue: https://oktainc.atlassian.net/browse/OKTA-865184

Remove `isSafari18`. Added `pollDelay` SDK option

---

CHANGELOG.md
lib/idx/types/idx-js.ts
lib/idx/webauthn.ts
test/spec/crypto/webauthn.ts
test/spec/idx/authenticate.ts
test/spec/idx/register.ts
test/support/idx/factories/remediations.ts

Updates the WebAuthn library to support Custom RP ID (Relying Party ID).
RP ID is a domain to which the WebAuthn enrollment is attached. It allows for creating an enrollment for a top level domain and having it work across all subdomains.

feat: adds `rpId` to credentials to add support for custom relying party id
