okta/okta-auth-js

- lib/cookies.js
- lib/index.js
- lib/reqwestRequest.js
- lib/util.js
bacon: test
Resolves: OKTA-89650
@rchild-okta
> Move utils to their own module

- lib/http.js
- lib/index.js
- lib/session.js
- lib/util.js
- package.json
- webpack.AMDJqueryQ.config.js
- webpack.config.js
bacon: test
Resolves: OKTA-89655
@rchild-okta 
@magizh-okta
> Modularize sessions and http

- lib/index.js
- lib/tx.js
- package.json
- webpack.AMDJqueryQ.config.js
- webpack.config.js
bacon: test
Resolves: OKTA-89669
@rchild-okta 
@magizh-okta
> Move tx to its own module

- webpack.config.js
bacon: test
Resolves: OKTA-91603
@rchild-okta
> Fix amd importing on umd build

- README.md
- package.json
> Updated README for better formatting against NPM

- lib/clientBuilder.js
- lib/token.js
- test/spec/general.js
- test/spec/token.js
- test/util/tokens.js
Resolves: OKTA-94712
@rchild-okta 
@stsai-okta
> Added authClient.token.decode

- .npmignore
Resolves: OKTA-95942
@rchild-okta 
@alexma-okta
> Reduce size of npm package

- lib/TokenManager.js
- lib/clientBuilder.js
- lib/token.js
- lib/util.js
- test/spec/general.js
- test/spec/oauth.js
- test/spec/token.js
- test/spec/tokenManager.js
- test/util/oauthUtil.js
- test/util/tokens.js
Resolves: OKTA-94715
@rchild-okta 
@manueltanzi-okta
> Add tokenManager.refresh

- .eslintrc.json
- lib/TokenManager.js
- lib/tokenStorageBuilder.js
- package.json
- test/spec/tokenManager.js
- test/util/oauthUtil.js
- test/util/tokens.js
Resolves: OKTA-94717 and OKTA-94716
@rchild-okta 
@manueltanzi-okta
> Added tokenManager.on/off/clear and autoRefresh

- lib/TokenManager.js
- test/spec/tokenManager.js
- test/util/oauthUtil.js
- test/util/util.js
Resolves: OKTA-97005
@rchild-okta 
@manueltanzi-okta
> Emit "expired" events when autoRefresh is disabled

- .npmignore
- .travis.yml
- Gruntfile.js
- ci-scripts/okta-auth-js-build.sh
- package.json
Resolves: OKTA-98831
@rchild-okta
> Ship dist directory

- lib/TokenManager.js
- lib/clientBuilder.js
- lib/token.js
- lib/util.js
- test/spec/token.js
- test/util/oauthUtil.js
Resolves: OKTA-97050
@rchild-okta @sergiymelnyk-okta
> Added token.refresh method

- lib/token.js
- test/spec/oauth.js
- test/spec/token.js
- test/util/oauthUtil.js
Resolves: OKTA-99859
@rchild-okta 
@haishengwu-okta
> Catch errors while building authorization url

- lib/TokenManager.js
- lib/token.js
- package.json
- test/spec/oauth.js
- test/spec/token.js
- test/spec/tokenManager.js
- test/util/oauthUtil.js
- test/util/tokens.js
Resolves: OKTA-96993
@rchild-okta 
@ravikanodia-okta
> Allow opening multiple iframes simultaneously

- lib/clientBuilder.js
- lib/token.js
- lib/util.js
Resolves: OKTA-94713
@rchild-okta 
@haishengwu-okta
> Deprecated idToken methods

- lib/token.js
> Fixed inconsistencies in client.token

- lib/clientBuilder.js
- lib/oauthUtil.js
- lib/token.js
- lib/util.js
- test/spec/oauth.js
- test/spec/oauthUtil.js
- test/spec/token.js
- test/spec/tokenManager.js
- test/util/oauthUtil.js
- test/util/tokens.js
- test/util/util.js
> Added issuer, authorizeUrl, and userinfoUrl

- README.md
Closes several gaps in our documentation
@rchild-okta 
@stsai-okta
> :memo: Updated docs with API and config info

- README.md
Clearly localhost doesn't work, so I fixed the links.
@alexma-okta 
Resolves: OKTA-113931
> :memo: Fixes localhost links in README.md

- lib/util.js
- test/spec/util.js
Resolves: OKTA-115460
@rchild-okta 
@jhe-okta
> :bug: Handles browsers without console

- lib/clientBuilder.js
- lib/token.js
- test/spec/token.js
- test/util/oauthUtil.js
- test/util/util.js
Resolves: OKTA-118266
@rchild-okta @magizh-okta
> :seedling: Remove hash after parsing tokens

- README.md
Resolves: OKTA-120630
Update scopes to show the ones here: http://developer.okta.com/docs/api/resources/oidc.html#scopes
@rchild-okta @eugenebakaiev-okta
> :memo: Add missing OIDC scopes to README

- .gitignore
- README.md
- lib/clientBuilder.js
- test/spec/fingerprint.js
- test/util/util.js
Migrating this functionality into auth-js from the widget:
https://github.com/okta/okta-signin-widget/blob/master/src/util/DeviceFingerprint.js
https://github.com/okta/okta-signin-widget/blob/master/test/unit/spec/DeviceFingerprint_spec.js
> :seedling: Add fingerprinting support

- lib/oauthUtil.js
- lib/util.js
- test/spec/oauthUtil.js
- test/spec/util.js
- IE 11 https://okta.box.com/s/3q6qr0xlxddaq7q0lr85j3nsn09wpx28
- IE 10 https://okta.box.com/s/5fiyqdrvin2s6ywt8r5wyjhjebgwpdf3
- https://oktainc.atlassian.net/browse/OKTA-161877
> Fix the okta-post-message reponse handling for IE10/11

- package.json
> Updates version of grunt-contrib-jasmine

- package-lock.json
Adds the `package-lock.json` file to pin dependencies.
> Adds package-lock.json

- CHANGELOG.md
- package-lock.json
- package.json
Set version to a patch version, update changelog
> Prep 2.0.1 release

- .vscode/launch.json
> :art: Add config for vscode debugger

- lib/tx.js
- test/spec/factor-enroll.js
- test/xhr/factor-enroll-activate-sms.js
- test/xhr/factor-enroll.js
- Adds support for `FACTOR_ENROLL` state in auth js
@mauriciocastillosilva-okta @robertdamphousse-okta @okta/idx @manueltanzi-okta 
Resolves: [OKTA-215034](https://oktainc.atlassian.net/browse/OKTA-215034)
> Add support for FACTOR_ENROLL state.

- lib/tx.js
- package.json
- test/spec/factor-enroll.js
- test/xhr/factor-enroll-activate-sms.js
- test/xhr/factor-enroll.js
Adds support for FACTOR_ENROLL state in auth js
@mauriciocastillosilva-okta @robertdamphousse-okta @okta/idx @manueltanzi-okta
Resolves: OKTA-215034
> feat: Add support for FACTOR_ENROLL state

- scripts/publish.sh
- scripts/setup.sh
- Fix publish script for version 1.17.0
@manueltanzi-okta @robertdamphousse-okta @jgao-okta
> Fix publish script

- README.md
Fix broken link to sdk guide docs
> docs: Fix broken sdk guide link

- CHANGELOG.md
- package.json
- 2.6.3 release: https://github.com/okta/okta-auth-js/releases/edit/untagged-34afbb9e93845a77f0d5
- 2.6.2 release: https://github.com/okta/okta-auth-js/releases/edit/untagged-a5446e61d0ff3bb3c354
> release: 2.6.3

- CHANGELOG.md
- packages/okta-auth-js/package.json
Includes redirect signout options
> release: 2.11

- packages/okta-auth-js/lib/oauthUtil.js
- packages/okta-auth-js/test/spec/oauthUtil.js
- test/support/util.js
- yarn.lock
See related issue: https://github.com/okta/okta-auth-js/issues/297
> fix: getWellKnown should use issuer, if configured

- .travis.yml
- packages/okta-auth-js/karma.conf.js
- packages/okta-auth-js/test/karma/spec/renewToken.js
- test/e2e/package.json
- test/e2e/wdio.conf.js
- yarn.lock
Fixes intermittent failure seen with karma tests. `mockWellKnown` needs to be setup before each test.
> fix: refreshToken test should mock well known before each test

- packages/okta-auth-js/lib/tx.js
- scripts/setup.sh
Resolves: OKTA-277229
@magizh-okta @aarongranick-okta @vijetmahabaleshwar-okta
> fix: update introspect API endpoint for v1

- CHANGELOG.md
- packages/okta-auth-js/lib/browser/browserStorage.js
- packages/okta-auth-js/lib/token.js
- packages/okta-auth-js/package.json
- packages/okta-auth-js/test/spec/cookies.js
- packages/okta-auth-js/test/spec/oauthUtil.js
- packages/okta-auth-js/test/spec/token.js
- packages/okta-auth-js/test/spec/tokenManager.js
- allows "3rd party" cookies by setting "sameSite: none"
- fixes issue when running inside an iframe: https://github.com/okta/okta-auth-js/issues/331
> fix: use sameSite: none for iframe compatibility

- packages/okta-auth-js/lib/oauthUtil.js
- packages/okta-auth-js/test/spec/oauthUtil.js
> feat: increase compatibility with hash router

- packages/okta-auth-js/lib/fetch/fetchRequest.js
- packages/okta-auth-js/test/spec/fetch-request.js
Resolves issue: https://github.com/okta/okta-auth-js/issues/347
> fix: omit cookies by default

- packages/okta-auth-js/lib/token.js
`getWithPopup` sets the responseMode to `okta_post_message`.
Removes unused/unreachable code involving `responseMode = fragment` for popups.
> removes unused/unreachable code (popup/fragment)

- scripts/publish.sh
Change target registry for publish
> Update build scripts

- package.json
- scripts/lint.sh
- scripts/publish.sh
- scripts/unit.sh
- test/app/src/testApp.ts
Previously all code was built in the setup script. Now each script builds what it needs. Also fixes TS error when running tests.
> fixes CI build

- package.json
- test/e2e/runner.js
- test/e2e/sauce.wdio.conf.js
> fixes EADDRESS in use error (wait for server to exit)

- README.md
How it looks now: https://github.com/shuowu-okta/test-markdown/blob/master/README.md
> doc: fix broken configuration table

- CHANGELOG.md
- README.md
- lib/TokenManager.ts
- test/spec/tokenManager.js
Merged into dev-4.1, let's add it into master, so we can have it in the new patch release.
> Sw fix infinite token renew okta 327536

- CHANGELOG.md
- lib/browser/browser.ts
- lib/token.ts
- package.json
- test/app/src/testApp.ts
- test/app/src/webpackEntry.ts
- test/e2e/pageobjects/TestApp.js
- test/e2e/specs/login.js
- test/e2e/util/loginUtils.js
- test/spec/browser.js
cherry picks fixes from 3.2 branch
> release: 4.0.2

- README.md
New PR from origin so tests will pass, closes #498
> README: fix typo on accessToken

- .eslintrc.json
- README.md
- env/index.js
- env/package.json
- lib/TokenManager.ts
- lib/browser/browser.ts
- package.json
- samples/README.md
- samples/generated/static-spa/public/app.js
- samples/generated/webpack-spa/src/index.js
- samples/templates/partials/spa/app.js
- samples/test/package.json
- samples/test/runner.js
- samples/test/sauce.wdio.conf.js
- samples/test/wdio.conf.js
- test/app/.eslintrc.js
- test/app/package.json
- test/app/public/static/index.html
- test/app/server.js
- test/app/webpack.config.js
- test/e2e/package.json
- test/e2e/sauce.wdio.conf.js
- test/e2e/wdio.conf.js
- test/spec/tokenManager.js
- yarn.lock
* fixes type  for `browser.getIdToken` and `browser.getAccessToken`
* adds warning message for tokenManager.add to use seTokens
* updates readme and test app
* fixes test script for samples
> fix: type fixes and suggest use setTokens over add

- README.md
> doc: fix readme broken url

- README.md
https://oktainc.atlassian.net/browse/OKTA-335137
> Update README.md file with Redirect to Okta information 

- lib/browser/browser.ts
- test/app/src/testApp.ts
- test/app/src/webpackEntry.ts
- test/e2e/pageobjects/TestApp.js
- test/e2e/specs/login.js
- test/e2e/util/loginUtils.js
- test/spec/browser.js
> backport fixes from 4.0.2

- CHANGELOG.md
- packages/okta-auth-js/lib/oauthUtil.js
- packages/okta-auth-js/test/spec/oauthUtil.js
- packages/okta-auth-js/test/spec/token.js
Origin PR: https://github.com/okta/okta-auth-js/pull/520
> Sw cherry pick login redirect code fix to 3.x

- CHANGELOG.md
- README.md
- jest.browser.js
- jest.server.js
- lib/OktaAuthBase.ts
- lib/browser/browser.ts
- lib/http.ts
- lib/oauthUtil.ts
- lib/token.ts
- package.json
- test/spec/http.js
- test/spec/oauthUtil.js
- test/spec/token.js
- test/support/oauthUtil.js
- test/support/util.js
Contains fixes from master which have not been released yet
> release 4.0.3

- lib/OktaAuth.ts
- lib/builderUtil.ts
- lib/types/OktaAuthOptions.ts
- lib/types/api.ts
- test/spec/OktaAuth/browser.ts
- test/spec/OktaAuth/constructor.ts
- test/spec/builderUtil.js
> revert original ua logic

- samples/test/features/account-unlock.feature
- samples/test/steps/when.ts
- samples/test/support/action/context-enabled/live-user/openEmailMagicLinkForEmailVerification.ts
- samples/test/support/action/context-enabled/live-user/openEmailMagicLinkForUnlock.ts
- samples/test/support/management-api/a18nClient.ts
* Adds cucumber feature test for email magic link unlock
* Clicking on the unlock account link should automatically unlock the user account on the browser
* Once unlocked user should be able to login
> Enables the Account Unlock using magic link feature test

- samples/test/features/self-service-registration.feature
* Adds cucumber test for user registration flow clicking magic link
* User should be able to register and login following the activation link
> Adds User registration feature test using email magic link

- docs/authn.md
Resolves https://github.com/okta/okta-auth-js/issues/1301
Internal ref: https://oktainc.atlassian.net/browse/OKTA-531830
> Fix authn readme for forgotPassword

- CHANGELOG.md
- lib/idx/types/idx-js.ts
- lib/idx/types/index.ts
- package.json
- test/types/auth-idx.test-d.ts
> chore: add uiDisplay property to IdxContext type

- CHANGELOG.md
- lib/idx/types/idx-js.ts
- test/types/auth-idx.test-d.ts
> fix: add `deviceKnown` property to `IdxAuthenticator` type

- lib/idx/interact.ts
- lib/idx/run.ts
- lib/idx/transactionMeta.ts
- lib/idx/types/meta.ts
- lib/idx/types/options.ts
- lib/oidc/types/options.ts
- lib/oidc/util/defaultTokenParams.ts
- test/spec/idx/interact.ts
- test/spec/oidc/util/defaultTokenParams.ts
- test/types/auth.test-d.ts
- Support `acrValues` in interaction code flow, added unit test
Internal ref: https://oktainc.atlassian.net/browse/OKTA-535364
> Support acrValues in interaction code flow

- CHANGELOG.md
- lib/idx/idxState/v1/idxResponseParser.ts
- lib/util/jsonpath.ts
- test/spec/util/jsonpath.ts
Copy of https://github.com/okta/okta-auth-js/pull/1342 for internal CI
> fix possible RCE in jsonpath-plus

- test/e2e/features/acr-values.feature
- test/e2e/features/enroll-authenticator.feature
- test/e2e/features/step-definitions/steps.ts
- test/e2e/pageobjects/OktaLogin.js
- test/e2e/specs/login.js
Internal ref: https://oktainc.atlassian.net/browse/OKTA-567457
> Fix e2e test for acr_values

- samples/config.js
- samples/generated/express-embedded-auth-with-sdk/web-server/routes/authenticator.js
- samples/generated/express-embedded-auth-with-sdk/web-server/utils/renderTemplate.js
- samples/generated/express-embedded-auth-with-sdk/web-server/views/authenticator.mustache
- samples/test/features/self-service-registration.feature
- samples/test/support/management-api/a18nClient.ts
- test/e2e/features/step-definitions/steps.ts
- test/e2e/pageobjects/OktaLogin.js
Internal ref: [OKTA-574495](https://oktainc.atlassian.net/browse/OKTA-574495)
> Fix e2e sample test failures for SSR

- lib/storage/BaseStorageManager.ts
- test/spec/oidc/OAuthStorageManager.ts
Resoves #1378
Internal ref: [OKTA-576319](https://oktainc.atlassian.net/browse/OKTA-576319)
> Fix server-side memory storage warning condition

- lib/myaccount/request.ts
- test/spec/myaccount/request.ts
Resolves https://github.com/okta/okta-auth-js/issues/1377
Internal ref: [OKTA-576318](https://oktainc.atlassian.net/browse/OKTA-576318)
> Fixes base url for MyAccount API requests

- README.md
This PR is in reference to #1396 to update readme marking v5 as retired.
Closes #1396.
> OKTA-602353 : Merging PR #1396

- package.json
- yarn.lock
> Upgrades `ansi-regex`, `got` to newer versions

- CHANGELOG.md
- lib/idx/types/api.ts
> Add `customLabel` to `Input` type

- CHANGELOG.md
- lib/http/types.ts
- lib/idx/remediators/Identify.ts
- samples/test/steps/when.ts
- samples/test/support/check/checkIsOnPage.ts
- test/e2e/features/step-definitions/steps.ts
- test/types/config.test-d.ts
- Added `rememberMe` to `IdentifyValues`
- `HttpRequestClient` returns `Promise<HttpResponse>` (Copy of https://github.com/okta/okta-auth-js/pull/1455)
> Type fixes

- CHANGELOG.md
- lib/myaccount/emailApi.ts
- lib/myaccount/passwordApi.ts
- lib/myaccount/phoneApi.ts
- lib/myaccount/profileApi.ts
- lib/myaccount/request.ts
- lib/myaccount/transactions/Base.ts
- lib/myaccount/transactions/EmailChallengeTransaction.ts
- lib/myaccount/transactions/EmailTransaction.ts
- lib/myaccount/transactions/PasswordTransaction.ts
- lib/myaccount/transactions/PhoneTransaction.ts
- lib/myaccount/types.ts
- lib/oidc/mixin/index.ts
- test/spec/myaccount/request.ts
Internal ref: OKTA-664667
Resolves #1471
> Fix Circular dependencies

- CHANGELOG.md
- lib/oidc/util/validateClaims.ts
- package.json
- test/spec/oidc/util/validateClaims.ts
This reverts commit 82b560227e3639a6a81e8506bc4b0a71c94794f3.
> Revert "Merge 1481 (#1482)"

- test/integration/spec/myaccount/phone.ts
See comments in 
https://oktainc.atlassian.net/browse/OKTA-686421
> Removes TODO comment, test snapshot verified to be accurate

- lib/idx/types/idx-js.ts
Small type fix for SIW
https://oktainc.atlassian.net/browse/OKTA-661650
> chore: Add nickname to IdxAuthenticator interface
